In [2]:
import multiprocessing
import numpy as np

In [ ]:

def printVal(value):
    return ("hello "*(value))
pool_obj = multiprocessing.Pool()
ans = pool_obj.map(printVal,range(0,4))
print(ans)
pool_obj.close()

['', 'hello ', 'hello hello ', 'hello hello hello ']


In [30]:
extra_keys = ["extra1", "extra2", "extra3"]
input_keys = ["input1", "input2"]

samples = np.array([np.linspace(0.0, 10, 9) for _ in input_keys]).T
print(samples)

[[ 0.    0.  ]
 [ 1.25  1.25]
 [ 2.5   2.5 ]
 [ 3.75  3.75]
 [ 5.    5.  ]
 [ 6.25  6.25]
 [ 7.5   7.5 ]
 [ 8.75  8.75]
 [10.   10.  ]]


In [27]:
def interp_eval(sam,vkey):
    sam1, sam2 = sam
    return sam1*2.0 + sam2

In [36]:
print(f"Postprocessing grid with extra keys: {extra_keys}")

def postproc(k):
    return [interp_eval(sam, vkey=k) for sam in samples]

output_samples = []
# for k in extra_keys:
#     output_samples.append(postproc(k))
# output_samples = np.array(output_samples).T

pool_obj = multiprocessing.Pool(processes=10)
ans = pool_obj.map(postproc,extra_keys)
output_samples = np.array([np.array(ans[i]) for i in range(len(extra_keys))]).T
print(np.shape(output_samples))

all_samples = np.hstack([samples, output_samples])
all_keys = list(input_keys) + extra_keys
print("    done")
print("")

print(all_samples)

Postprocessing grid with extra keys: ['extra1', 'extra2', 'extra3']
(9, 3)
    done

[[ 0.    0.    0.    0.    0.  ]
 [ 1.25  1.25  3.75  3.75  3.75]
 [ 2.5   2.5   7.5   7.5   7.5 ]
 [ 3.75  3.75 11.25 11.25 11.25]
 [ 5.    5.   15.   15.   15.  ]
 [ 6.25  6.25 18.75 18.75 18.75]
 [ 7.5   7.5  22.5  22.5  22.5 ]
 [ 8.75  8.75 26.25 26.25 26.25]
 [10.   10.   30.   30.   30.  ]]
